### ISSUE TITLE
App crash on android

### ISSUE THREAD

**Issue by hakymz** [maitrungduc1410/react-native-video-trim#46]
When I call the show showEditor it crashes the app on android but it works fine on ios. Please what can be the issue?

**Comment by maitrungduc1410** [comment]
hi, can you wrap some log in Logcat (Android studio) at the time it's crashed?

**Comment by hakymz** [comment]
am using react native how do i go about that?

**Comment by maitrungduc1410** [comment]
Note that you have to use real device for both android and + ios

And to get Android log: open Android studio-> Logcat -> select your physical device -> run-android -> test your app, on crash there should be some red error log printed

**Comment by hakymz** [comment]
ok i have real device

**Comment by hakymz** [comment]
FATAL EXCEPTION: main
                                                                                                    Process: com.hklive, PID: 17345
                                                                                                    java.lang.IllegalArgumentException: /picker/0/com.android.providers.media.photopicker/media/1000179502 does not exist
                                                                                                    	at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java:255)
                                                                                                    	at com.videotrim.widgets.ZVideoView.setVideoURI(ZVideoView.java:32)
                                                                                                    	at com.videotrim.widgets.VideoTrimmerView.initVideoByURI(VideoTrimmerView.java:154)
                                                                                                    	at com.videotrim.VideoTrimModule.lambda$showEditor$1$com-videotrim-VideoTrimModule(VideoTrimModule.java:113)
                                                                                                    	at com.videotrim.VideoTrimModule$$ExternalSyntheticLambda4.run(Unknown Source:8)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:942)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:204)
                                                                                                    	at android.os.Looper.loop(Looper.java:291)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8134)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:588)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1019)




this is the error

**Comment by maitrungduc1410** [comment]
> java.lang.IllegalArgumentException: /picker/0/com.android.providers.media.photopicker/media/1000179502 does not exist


as the error shows above, high change your video is invalid, the error is thrown by native Android `MediaMetadataRetriever` not which is not my lib. You may want to try with `react-native-image-picker` to see if it works

**Comment by hakymz** [comment]
I checked with the isValidVideo function provided it returns true, also the video plays with react-native-video and I am react-native-image-picker and using android 13

**Comment by maitrungduc1410** [comment]
Can you provide me your input video?

Also which android version are you using? On which model device?

**Comment by abhishekgupta2144** [comment]
Facing the same issue app is crashing when showEditor is called.

**Comment by maitrungduc1410** [comment]
@abhishekgupta2144 can you provide your env details, platform + your code + test video?

**Comment by abhishekgupta2144** [comment]
platform  is android version 34,
video url = content://media/external_primary/video/media/1000141719,

useEffect(() => {
    const eventEmitter = new NativeEventEmitter(NativeModules.VideoTrim);
    console.log("eventEmitter :", eventEmitter);
    const subscription = eventEmitter.addListener("VideoTrim", (event) => {
      console.log("event :", event);
      switch (event.name) {
        case "onShow": {
          console.log("onShowListener", event);
          break;
        }
        case "onHide": {
          console.log("onHide", event);
          break;
        }
        case "onStartTrimming": {
          console.log("onStartTrimming", event);
          break;
        }
        case "onFinishTrimming": {
          console.log("onFinishTrimming", event);
          const outputPath = event.outputPath.startsWith("file://")
            ? event.outputPath
            : "content://" + event.outputPath;
          setResultVideo(outputPath);
          console.log("outputPath :", outputPath);
          checkVideoUrl(outputPath);
          break;
        }
        case "onCancelTrimming": {
          console.log("onCancelTrimming", event);
          break;
        }
        case "onError": {
          console.log("onError", event);
          break;
        }
      }
    });
    console.log("subscription :", subscription);
    return () => {
      subscription.remove();
    };
  }, []);

<TouchableOpacity
  onPress={async () => {
    try {
      const result = share.data.toString();
      console.log("result :", Platform);
      const outputPath = await showEditor(
        result || "",
        {
          maxDuration: 20,
        }
      );
      console.log(
        "Editing completed. Output path:",
        outputPath
      );
      setResultVideo(outputPath);
      checkVideoUrl(outputPath);
    } catch (error) {
      console.error("Error editing video:", error);
    }
  }}
  style={{ padding: 10, backgroundColor: "red" }}
>
  <Text>Edit</Text>
</TouchableOpacity>

**Comment by maitrungduc1410** [comment]
what i meant is real video, can you upload it here?

**Comment by maitrungduc1410** [comment]
and it's still very hard for me to debug your issue. make sure you're using real device

Can you help me do this: Open Android studio > Logcat, make sure your device is connected -> run debug on your device.

Observe Logcat, when it's crashed, there should be some errors there (those in red color), copy and send me those errors

**Comment by abhishekgupta2144** [comment]
https://github.com/maitrungduc1410/react-native-video-trim/assets/95283122/c9bcb1e6-97ec-4794-93c9-8b5c84e17d20

**Comment by abhishekgupta2144** [comment]
FATAL EXCEPTION: main
                                                                                                    Process: com.memorizz, PID: 9597
                                                                                                    java.lang.IllegalArgumentException: /external_primary/video/media/1000035362 does not exist
                                                                                                    	at android.media.MediaMetadataRetriever.setDataSource(MediaMetadataRetriever.java:262)
                                                                                                    	at com.videotrim.widgets.ZVideoView.setVideoURI(ZVideoView.java:32)
                                                                                                    	at com.videotrim.widgets.VideoTrimmerView.initVideoByURI(VideoTrimmerView.java:154)
                                                                                                    	at com.videotrim.VideoTrimModule.lambda$showEditor$1$com-videotrim-VideoTrimModule(VideoTrimModule.java:113)
                                                                                                    	at com.videotrim.VideoTrimModule$$ExternalSyntheticLambda4.run(Unknown Source:8)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:938)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:233)
                                                                                                    	at android.os.Looper.loop(Looper.java:344)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8212)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)

**Comment by maitrungduc1410** [comment]
@abhishekgupta2144 as the error shows, the file doesn't exist. What library you're using for video picker? version?

**Comment by abhishekgupta2144** [comment]
This file uri can be played and shown through react-native-video it means the path coming is correct. And i am just passing the file path to the showEditor(). And it is opening the editor with the same process on ios devices and crashing the app on android.

**Comment by maitrungduc1410** [comment]
@abhishekgupta2144 I believe, when you pass that URL to react-native-video, they'll do some transformation under the hood to parse the URL for you

**Comment by maitrungduc1410** [comment]
you can use `isValidVideo` to check for that

**Comment by abhishekgupta2144** [comment]
@maitrungduc1410 Tried but In android, the output is coming true as my video url is valid.

**Comment by abhishekgupta2144** [comment]
@maitrungduc1410 could you found that issue ?

**Comment by maitrungduc1410** [comment]
Not yet, sorry for late reply, I can't reproduce the case, still trying to figure why

**Comment by abhishekgupta2144** [comment]
I think for android it only supports url through [react-native-image-picker](https://github.com/react-native-image-picker/react-native-image-picker) library for video editing.

**Comment by maitrungduc1410** [comment]
@abhishekgupta2144 not like that, my lib is designed to work independently from any picker lib, the URL you get from rn-video maybe a temporary URL

**Comment by terence1990** [comment]
@abhishekgupta2144  try something like `filePath.startsWith('file://') ? filePath : \`file://${filePath}\``

**Comment by maitrungduc1410** [comment]
please upgrade to `^2.1.0`, you can listen to `onLog` event, from there you should be able to know what's going on
